//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 09:49:37 PM GMT 
//


package com.dimitrisli.jaxb.producedClasses;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ShipInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShipVia" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ShipName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipPostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ShippedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipInfoType", propOrder = {
    "shipVia",
    "freight",
    "shipName",
    "shipAddress",
    "shipCity",
    "shipRegion",
    "shipPostalCode",
    "shipCountry"
})
public class ShipInfoType {

    @XmlElement(name = "ShipVia", required = true)
    protected BigInteger shipVia;
    @XmlElement(name = "Freight", required = true)
    protected BigDecimal freight;
    @XmlElement(name = "ShipName", required = true)
    protected String shipName;
    @XmlElement(name = "ShipAddress", required = true)
    protected String shipAddress;
    @XmlElement(name = "ShipCity", required = true)
    protected String shipCity;
    @XmlElement(name = "ShipRegion", required = true)
    protected String shipRegion;
    @XmlElement(name = "ShipPostalCode", required = true)
    protected String shipPostalCode;
    @XmlElement(name = "ShipCountry", required = true)
    protected String shipCountry;
    @XmlAttribute(name = "ShippedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar shippedDate;

    /**
     * Gets the value of the shipVia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShipVia() {
        return shipVia;
    }

    /**
     * Sets the value of the shipVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShipVia(BigInteger value) {
        this.shipVia = value;
    }

    /**
     * Gets the value of the freight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * Sets the value of the freight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreight(BigDecimal value) {
        this.freight = value;
    }

    /**
     * Gets the value of the shipName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipName() {
        return shipName;
    }

    /**
     * Sets the value of the shipName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipName(String value) {
        this.shipName = value;
    }

    /**
     * Gets the value of the shipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipAddress() {
        return shipAddress;
    }

    /**
     * Sets the value of the shipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipAddress(String value) {
        this.shipAddress = value;
    }

    /**
     * Gets the value of the shipCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipCity() {
        return shipCity;
    }

    /**
     * Sets the value of the shipCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipCity(String value) {
        this.shipCity = value;
    }

    /**
     * Gets the value of the shipRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipRegion() {
        return shipRegion;
    }

    /**
     * Sets the value of the shipRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipRegion(String value) {
        this.shipRegion = value;
    }

    /**
     * Gets the value of the shipPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipPostalCode() {
        return shipPostalCode;
    }

    /**
     * Sets the value of the shipPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipPostalCode(String value) {
        this.shipPostalCode = value;
    }

    /**
     * Gets the value of the shipCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipCountry() {
        return shipCountry;
    }

    /**
     * Sets the value of the shipCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipCountry(String value) {
        this.shipCountry = value;
    }

    /**
     * Gets the value of the shippedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getShippedDate() {
        return shippedDate;
    }

    /**
     * Sets the value of the shippedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setShippedDate(XMLGregorianCalendar value) {
        this.shippedDate = value;
    }

}
